FacultyInformationSystemWebAppClient/Controllers/CourseController.cs
using FacultyInformationSystemEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace FacultyInformationSystemWebAppClient.Controllers
{
    [Authorize]
    public class CourseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        //[Route("GetNewCourse")]
        public async Task<IActionResult> GetCourse(int? Id)
        {

            //int facultyId = (int)TempData["facultyId"];
            //TempData["facultyId"] = facultyId;
            HttpClient httpClient = new HttpClient();
            //StringContent content = new StringContent(); // Post
            string Url = "https://localhost:44317/api/Admin/GetCourses";
            var result = await httpClient.GetAsync(Url);
            var jsonData = result.Content.ReadAsStringAsync();

            var clientData = JsonConvert.DeserializeObject<List<Course>>(jsonData.Result);

            if (clientData != null)
            {
                return View(clientData);
            }

            return NotFound();
        }

        [HttpGet]
        //[Route("CreateNewCourse")]
        public async Task<IActionResult> CreateNewCourse()
        {
            HttpClient httpClient = new HttpClient();
            string deptUrl = "https://localhost:44317/api/Admin/GetDepartment";
            var resultUrl = await httpClient.GetAsync(deptUrl);
            var jsonDataResult = resultUrl.Content.ReadAsStringAsync();

            var departmentData = JsonConvert.DeserializeObject<List<Department>>(jsonDataResult.Result);

            ViewBag.DepartmentList = departmentData.ToList();
            return View();
        }

        [HttpPost]
        //[Route("PostCourse")]
        public async Task<IActionResult> CreateNewCourse(Course course)
        {

            if (ModelState.IsValid)
            {
                HttpClient client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(course), null, "application/json");
                var response = await client.PostAsync("https://localhost:44317/api/Admin/PostAddCourses", content);

                var jsonData = response.Content.ReadAsStringAsync();

                var clientData = JsonConvert.DeserializeObject<Course>(jsonData.Result);

                if (clientData != null)
                {
                    return RedirectToAction("GetCourse");
                }
            }
            HttpClient httpClient = new HttpClient();
            string deptUrl = "https://localhost:44317/api/Admin/GetDepartment";
            var resultUrl = await httpClient.GetAsync(deptUrl);
            var jsonDataResult = resultUrl.Content.ReadAsStringAsync();

            var departmentData = JsonConvert.DeserializeObject<List<Department>>(jsonDataResult.Result);

            ViewBag.DepartmentList = departmentData.ToList();

            return View();
        }



        [HttpGet]
        public async Task<IActionResult> UpdateCourse(int Id)
        {
            HttpClient httpClient = new HttpClient();
            string Url = "https://localhost:44317/api/Admin/GetCourses";
            var result = await httpClient.GetAsync(Url);
            var jsonData = result.Content.ReadAsStringAsync();

            var clientData = JsonConvert.DeserializeObject<List<Course>>(jsonData.Result);

            var courseObj = clientData.Where(m => m.CourseId == Id).FirstOrDefault();

            string deptUrl = "https://localhost:44317/api/Admin/GetDepartment";
            var resultUrl = await httpClient.GetAsync(deptUrl);
            var jsonDataResult = resultUrl.Content.ReadAsStringAsync();

            var departmentData = JsonConvert.DeserializeObject<List<Department>>(jsonDataResult.Result);

            ViewBag.DepartmentList = departmentData.ToList();

            return View(courseObj);

        }

        [HttpPost]
        public async Task<IActionResult> UpdateCourse(Course course)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(course), null, "application/json");
                var response = await client.PostAsync("https://localhost:44317/api/Admin/UpdateCourse", content);

                var jsonData = response.Content.ReadAsStringAsync();

                var clientData = JsonConvert.DeserializeObject<Course>(jsonData.Result);

                if (clientData != null)
                {

                    return RedirectToAction("GetCourse");
                }
            }
            HttpClient httpClient = new HttpClient();
            string deptUrl = "https://localhost:44317/api/Admin/GetDepartment";
            var resultUrl = await httpClient.GetAsync(deptUrl);
            var jsonDataResult = resultUrl.Content.ReadAsStringAsync();

            var departmentData = JsonConvert.DeserializeObject<List<Department>>(jsonDataResult.Result);

            ViewBag.DepartmentList = departmentData.ToList();
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> DeleteCourse(int Id)
        {
            //int facultyId = (int)TempData["facultyId"];
            //TempData["facultyId"] = facultyId;
            HttpClient httpClient = new HttpClient();
            //StringContent content = new StringContent(); // Post
            string Url = "https://localhost:44317/api/Admin/DeleteCourse?CourseId=" + Id.ToString();
            var result = await httpClient.DeleteAsync(Url);


            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("GetCourse");
            }

            return View();
        }
    }
}

FacultyInformationSystemWebAppClient/Controllers/DepartmentController.cs
using FacultyInformationSystemEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace FacultyInformationSystemWebAppClient.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        //[Route("GetNewDepartment")]
        public async Task<IActionResult> GetDepartment(int? Id)
        {

            //int facultyId = (int)TempData["facultyId"];
            //TempData["facultyId"] = facultyId;
            HttpClient httpClient = new HttpClient();
            //StringContent content = new StringContent(); // Post
            string Url = "https://localhost:44317/api/Admin/GetDepartment";
            var result = await httpClient.GetAsync(Url);
            var jsonData = result.Content.ReadAsStringAsync();

            var clientData = JsonConvert.DeserializeObject<List<Department>>(jsonData.Result);


            if (clientData != null)
            {
                return View(clientData);
            }

            return NotFound();
        }

        [HttpGet]
        //[Route("CreateNewDepartment")]
        public IActionResult CreateNewDepartment()
        {
            return View();
        }

        [HttpPost]
        //[Route("PostDepartment")]
        public async Task<IActionResult> CreateNewDepartment(Department department)
        {

            if (ModelState.IsValid)
            {
                HttpClient client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(department), null, "application/json");
                var response = await client.PostAsync("https://localhost:44317/api/Admin/PostAddDepartment", content);

                var jsonData = response.Content.ReadAsStringAsync();

                var clientData = JsonConvert.DeserializeObject<Department>(jsonData.Result);


                if (clientData != null)
                {
                    return RedirectToAction("GetDepartment");
                }

            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> UpdateDepartment(int Id)
        {
            HttpClient httpClient = new HttpClient();
            string Url = "https://localhost:44317/api/Admin/GetDepartment";
            var result = await httpClient.GetAsync(Url);
            var jsonData = result.Content.ReadAsStringAsync();

            var clientData = JsonConvert.DeserializeObject<List<Department>>(jsonData.Result);
            var departmentObj = clientData.Where(m => m.DeptId == Id).FirstOrDefault();

            return View(departmentObj);

        }

        [HttpPost]
        public async Task<IActionResult> UpdateDepartment(Department department)
        {
            if (ModelState.IsValid)
            {
                HttpClient client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(department), null, "application/json");
                var response = await client.PostAsync("https://localhost:44317/api/Admin/UpdateDepartment", content);

                var jsonData = response.Content.ReadAsStringAsync();

                var clientData = JsonConvert.DeserializeObject<Department>(jsonData.Result);

                if (clientData != null)
                {
                    return RedirectToAction("GetDepartment");
                }
            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> DeleteDepartment(int Id)
        {
            //int facultyId = (int)TempData["facultyId"];
            //TempData["facultyId"] = facultyId;
            HttpClient httpClient = new HttpClient();
            //StringContent content = new StringContent(); // Post
            string Url = "https://localhost:44317/api/Admin/DeleteDepartment?Id=" + Id.ToString();
            var result = await httpClient.DeleteAsync(Url);


            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("GetDepartment");
            }

            return View();
        }

    }
}

FacultyInformationSystemWebAppClient/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FacultyInformationSystemWebAppClient.Controllers
{
    public class MainController : Controller
    {
        // Returns home view.
        public ActionResult Home()
        {
            return View();
        }

        // Returns about view.
        public ActionResult About()
        {
            return View();
        }

        // Returns contact view.
        public ActionResult Contact()
        {
            return View();
        }

        // Returns login view.
        public ActionResult Login()
        {
            return View();
        }
    }
}

FacultyInformationSystemWebAppClient/Controllers/StudentController.cs
using FacultyInformationSystemEntities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace FacultyInformationSystemWebAppClient.Controllers
{

    [Authorize]
    public class StudentController : Controller
    {
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }

        public async Task<IActionResult> GetFacultyIndex()
        {
            HttpClient httpClient = new HttpClient();
            //StringContent content = new StringContent(); // Post
            string Url = "https://localhost:44317/api/Admin/GetFacultyList";
            var result = await httpClient.GetAsync(Url);
            var jsonData = result.Content.ReadAsStringAsync();

            var clientData = JsonConvert.DeserializeObject<List<Faculty>>(jsonData.Result);
            if (clientData == null)
            {
                return NotFound();
            }

            ViewBag.FacultyList = clientData;

            return View();
        }


        [HttpPost]
        //[Route("GetPublications")]
        public IActionResult PostPublications(Faculty faculty)
        {

            if (faculty != null)
            {
                return RedirectToAction("GetPublicationsStudent", "Publication", new { Id = faculty.FacultyId });
            }
            return View();

        }


        public IActionResult Index()
        {

            return View();
        }
    }
}

FacultyInformationSystemWebAppClient/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Capgemini</title>
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/lmscustom.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <style>
        /*body {
            background-color: #808080;
        }*/
        .dropbtn {
            background-color: orange;
            color: white;
            padding: 16px;
            font-size: 16px;
            border: none;
        }
        /*
        .dropdown {
            position: relative;
            display: inline-block;
        }*/

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: orange;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #ffed97;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: orange;
        }
    </style>

</head>
<body style="padding:unset">
    <div>
        <div style="background-color:darkblue;">
            <div style="background-color:yellow; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
            <span class="icon">
            </span>
            @Html.ActionLink("Vignan", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-danger text-light">
                        @*<i class="fas fa-home"></i>*@
                        @Html.ActionLink("Home", "Index", "Admin", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-danger text-light">
                        @*<i class="fas fa-address-card"></i>*@
                        @Html.ActionLink("About", "About", "Admin", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-danger text-light">
                        @*<i class="fas fa-id-badge"></i>*@
                        @Html.ActionLink("Contact", "Contact", "Admin", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px; padding-top:5px; padding-bottom:7px; font-size: 15px">

                        <div class="nav-item btn-sm btn-warning text-dark" title="Register">
                            <a class="text-dark" asp-area="Identity" asp-page="/Account/Register">AddUser</a>
                        </div>


                        @*@Html.ActionLink("AddUser", "AddUser", "Admin", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })*@
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px; padding-top:8px; padding-bottom:8px; font-size: 15px">

                        @Html.ActionLink("Courses", "GetCourse", "Course", null, new { @class = "nav-item btn-sm btn-warning text-dark", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px; padding-top:8px; padding-bottom:8px; font-size: 15px">
                        @Html.ActionLink("Subjects", "GetSubject", "Admin", null, new { @class = "nav-item btn-sm btn-warning text-dark", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px; padding-top:8px; padding-bottom:8px; font-size: 15px">
                        @Html.ActionLink("FacultyJob", "FacultyIndex", "Admin", null, new { @class = "nav-item btn-sm btn-warning text-dark", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px; padding-top:8px; padding-bottom:8px; font-size: 15px">
                        @Html.ActionLink("Departments", "GetDepartment", "Department", null, new { @class = "nav-item btn-sm btn-warning text-dark", style = "text-decoration:none;" })
                    </li>
                    <li class="" style="padding-left: 5px; padding-right: 5px; padding-top:8px; padding-bottom:8px; font-size: 15px">
                        @Html.ActionLink("Designation", "GetDesignation", "Admin", null, new { @class = "nav-item btn-sm btn-warning text-dark", style = "text-decoration:none;" })
                    </li>

                    <li class="" style="padding-left:1px; padding-right:6px">

                        <div class="btn btn-sm dropdown">
                            <button class="btn btn-sm btn-warning text-dark">Publications</button>
                            <div class="dropdown-content">
                                <a class="text-dark" asp-action="GetFilterIndex" asp-controller="Publication" asp-route-id="1">Yearly</a>
                                <a class="text-dark" asp-action="GetFilterIndex" asp-controller="Publication" asp-route-id="2">Monthly</a>
                                <a class="text-dark" asp-action="GetFilterIndex" asp-controller="Publication" asp-route-id="3">Recent</a>

                            </div>
                        </div>
                    </li>

                    @*<li class="" style="padding-left:5px; padding-right:10px">
                            @Html.ActionLink("Return", "Return", "AdminTransaction", null, new { @class = "nav-item btn-sm btn-primary text-light", style = "text-decoration:none;" })
                        </li>*@
                </ul>


                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" @*asp-area="Identity" asp-page="/Account/Manage/Index"*@ title="Manage">Hello @User.Identity.Name!</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline text-primary btn-light" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link btn-light text-primary">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {

                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>*@

                        <li class="nav-item">
                            <button class="btn btn-danger">
                                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </button>

                        </li>

                    }
                </ul>

            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-white bg-danger">
                <div class="card-header">
                    Thank you for your work
                </div>
                <div class="card-body">

                    <p>&copy; @DateTime.Now.Year - FacultyInformationSystem</p>
                </div>
            </div>
        </footer>
    </div>
    <div style="background-color:darkblue;">
        <div style="background-color:yellow; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

FacultyInformationSystemWebAppClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacultyInformationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-color: #808080;
        }
    </style>
</head>
<body>
    <div>
        <div style="background-color:#ff0000;">
            <div style="background-color:#ffd800; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <span class="icon">
                <i class="fas fa-book-open"></i>
            </span>
            @Html.ActionLink("Vignan", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">



                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-home"></i>
                        @Html.ActionLink("Home", "Index", "Home", new { @class = "nav-link icon", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-address-card"></i>
                        @Html.ActionLink("Privacy", "Privacy", "Home", new { @class = "nav-link icon", style = "display:inline" })
                    </li>

                </ul>

                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item btn-sm btn-dark">
                        <i class="fas fa-sign-in-alt"></i>
                        @*<partial name="_LoginPartial" />*@
                        <button class="btn btn-light">
                            @*<a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>*@
                            @Html.ActionLink("Login", "Login", "Main", new { @class = "nav-link icon", style = "display:inline" })
                        </button>


                    </li>
                </ul>
            </div>
        </nav>

    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div>
        <footer>
            <div style="" class="card text-center text-white bg-dark">
                <div class="card-header">
                    Thank you for visiting us
                </div>
                <p>&copy; @DateTime.Now.Year - FacultyInformationSystem</p>
            </div>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

FacultyInformationSystemWebAppClient/Views/Shared/_StudentLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Capgemini</title>
    <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/lmscustom.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body style="padding:unset">
    <div>
        <div style="background-color:#d9534f;">
            <div style="background-color:#ffd800; height:8px; width:450px">
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <span class="icon">
            </span>
            @Html.ActionLink("Vignan", "Index", "Student", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item btn-sm btn-primary">
                        @*<i class="fas fa-home"></i>*@
                        @Html.ActionLink("Home", "Index", "Student", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-primary">
                        @*<i class="fas fa-address-card"></i>*@
                        @Html.ActionLink("About", "About", "Student", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                    <li class="nav-item btn-sm btn-primary">
                        @*<i class="fas fa-id-badge"></i>*@
                        @Html.ActionLink("Contact", "Contact", "Student", new { area = "" }, new { @class = "nav-link", style = "display:inline" })
                    </li>
                </ul>
                <ul class="navbar-nav justify-content-end" style="padding-right:50px">
                    <li class="" style="padding-left:5px; padding-right:5px">

                        @Html.ActionLink("Publications", "GetFacultyIndex", "Student", new { Id = UserManager.GetUserId(User) }, new { @class = "nav-item btn-sm btn-light text-dark", style = "text-decoration:none;" })
                    </li>

                </ul>


                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline text-primary btn-light" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link btn-light text-primary">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {

                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </li>*@

                        <li class="nav-item">
                            <button class="btn btn-primary">
                                <a class="nav-link text-light" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            </button>

                        </li>

                    }
                </ul>

            </div>
        </nav>
    </div>
    <div style="padding-left:20px; padding-right:20px">
        @RenderBody()
    </div>
    <div>

        <footer>
            <div style="" class="card text-center text-white bg-primary">
                <div class="card-header">
                    Thank you for your work
                </div>
                <div class="card-body">

                    <p>&copy; @DateTime.Now.Year - FacultyInformationSystem</p>
                </div>
            </div>
        </footer>
    </div>
    <div style="background-color:#d9534f;">
        <div style="background-color:#ffd800; height:8px; width:450px">
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>